services:
  - type: web
    name: coffee-shop-api  # Tên service trên Render
    env: python
    repo: https://github.com/jjoevv/coffee-shop.git  # Thay bằng repo của bạn
    branch: main
    plan: free  # Sử dụng plan miễn phí, có thể đổi thành "starter", "pro"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Nếu dùng Flask, thay bằng lệnh start tương ứng
    envVars:
      - key: MONGO_URL
        sync: false  # Nếu bạn đã đặt biến này trên Render UI
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: 10000
